[workspace]
members = [
    "ublox-cellular",
    "examples/common_lib",
    "examples/linux",
    "examples/linux_mqtt",
    # "examples/linux_jobs",
]


[patch.crates-io]
serde_at = { git = "https://github.com/BlackbirdHQ/atat", branch = "master" }
atat = { git = "https://github.com/BlackbirdHQ/atat", branch = "master" }
mqttrs = { path = "../mqttrs" }

# [patch.'https://github.com/thejpster/embedded-nal']
# embedded-nal = { git = "https://github.com/MathiasKoch/embedded-nal", branch = "factbird_mini" }
