[workspace]
members = [
    "ublox-cellular",
    # "examples/common_lib",
    # "examples/linux",
    # "examples/linux_mqtt",
    # "examples/linux_jobs",
]

[patch."https://github.com/BlackbirdHQ/embedded-nal"]
embedded-nal = { path = "/home/kei/Blackbird/GitHub/embedded-nal" }
