[package]
name = "ublox-cellular-rs"
version = "0.0.1"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "Driver crate for u-blox cellular devices, implementation follows 'UBX-14044127 - R40'"
readme = "README.md"
keywords = ["arm", "cortex-m", "ublox", "cellular"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/ublox-cellular-rs"
edition = "2018"

[lib]
name = "ublox_cellular"
doctest = false

[dependencies]
heapless = { version = "0.5.3", features = ["serde"] }
no-std-net = { version = "0.3.0", features = ["serde"] }
embedded-hal = "0.2.3"
nb = "0.1.2"
atat = { version = "^0.3.0", features = ["derive"] }
serde_at = { version = "^0.3.0" }
serde = { version = "^1", default-features = false, features = ["derive"] }
serde_repr = "0.1"
ufmt = { version = "0.1.0", optional = true }
embedded-nal = { git = "https://github.com/thejpster/embedded-nal" }
hex = { version = "0.4.2", default-features = false }
log = { version = "0.4", default-features = false, optional = true }


[dev-dependencies]
env_logger = "0.7.1"
void = { version = "1.0.2", default-features = false }
linux-embedded-hal = "0.3.0"
serialport = "3.3.0"
mqttrust = { git = "https://github.com/BlackbirdHQ/mqttrust" }

[patch.crates-io]
# atat = { git = "https://github.com/BlackbirdHQ/atat" }
# serde_at = { git = "https://github.com/BlackbirdHQ/atat" }
atat = { path = "../atat/atat" }
serde_at = { path = "../atat/serde_at" }

[features]
default = ["sara_u2", "socket-udp", "socket-tcp", "use_ufmt"]

topy_l4 = []
mpci_l2 = []
lisa_u2 = []
sara_g3 = []
sara_g4 = []
sara_u2 = []
sara_u1 = []
toby_l2 = []
toby_r2 = []
lara_r2 = []
leon_g1 = []

socket-tcp = []
socket-udp = []
use_ufmt = ["ufmt"]
logging = ["log"]
