[package]
name = "ublox-cellular-rs"
version = "0.4.0"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "Driver crate for u-blox cellular devices, implementation follows 'UBX-13002752 - R65'"
readme = "../README.md"
keywords = ["arm", "cortex-m", "ublox", "cellular", "embedded-hal-driver"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/ublox-cellular-rs"
edition = "2021"

[lib]
name = "ublox_cellular"
doctest = false

[dependencies]
atat = { version = "0.20.0", features = ["derive", "bytes"] }
embedded-hal = "=1.0.0-rc.1"
embedded-nal = "0.7"
hash32 = "^0.3"
heapless = { version = "^0.8", features = ["serde"] }
nb = "^1"
serde = { version = "^1", default-features = false, features = ["derive"] }
ublox-sockets = { version = "0.5", optional = true }
embassy-time = "0.1.5"
embassy-sync = "0.4"

no-std-net = { version = "^0.6", features = ["serde"] }

log = { version = "^0.4", default-features = false, optional = true }
defmt = { version = "^0.3", optional = true }

embedded-nal-async = { version = "0.6", optional = true }
futures-util = { version = "0.3.29", default-features = false }
#futures = { version = "0.3.17", default-features = false, features = [
#    "async-await",
#] }

embassy-futures = { version = "0.1", optional = true }

embedded-io = "0.6"
embedded-io-async = "0.6"

[features]
default = ["socket-udp", "socket-tcp", "async", "ublox-sockets"]

async = ["dep:embedded-nal-async", "dep:embassy-futures", "atat/async", "ublox-sockets?/async"]

defmt = [
    "dep:defmt",
    "ublox-sockets?/defmt",
    "atat/defmt",
    "heapless/defmt-03",
    "embassy-time/defmt",
    "embassy-sync/defmt",
    "embassy-futures?/defmt",
]

log = ["dep:log", "ublox-sockets?/log", "atat/log"]

lara-r2 = []
lara-r6 = []
leon-g1 = []
lisa-u2 = []
mpci-l2 = []
sara-g3 = []
sara-g4 = []
sara-r5 = ["upsd-context-activation"]
sara-u1 = []
sara-u2 = ["upsd-context-activation"]
toby-l2 = []
toby-r2 = []
toby-l4 = []

upsd-context-activation = []

socket-tcp = ["ublox-sockets?/socket-tcp"]
socket-udp = ["ublox-sockets?/socket-udp"]

[workspace]
members = []
default-members = ["."]
exclude = ["examples"]

[patch.crates-io]
ublox-sockets = { git = "https://github.com/BlackbirdHQ/ublox-sockets", branch = "feature/async-borrowed-sockets" }
no-std-net = { git = "https://github.com/rushmorem/no-std-net", branch = "issue-15" }
#ublox-sockets = { path = "../ublox-sockets" }
atat = { path = "../atat/atat" }
