[workspace]
members = [
    "ublox-cellular",
    # "examples/common_lib",
    # "examples/linux",
    # "examples/linux_mqtt",
    # "examples/linux_jobs",
]


[patch.crates-io]
atat = { path = "../atat/atat" }
embedded-nal = { path = "../embedded-nal" }
