[workspace]
members = [
    "ublox-cellular",
    "examples/common_lib",
    "examples/linux",
    "examples/linux_mqtt",
    "examples/linux_jobs",
]


[patch.crates-io]
# atat = { git = "https://github.com/BlackbirdHQ/atat" }
serde_at = { git = "https://github.com/BlackbirdHQ/atat" }
atat = { path = "../atat/atat" }
# serde_at = { path = "../atat/serde_at" }

[patch.'https://github.com/thejpster/embedded-nal']
embedded-nal = { path = "../embedded-nal" }
