[workspace]
resolver = "2"
members = [
    "ublox-cellular",
    # "examples/common_lib",
    # "examples/linux",
    # "examples/linux_mqtt",
    # "examples/linux_jobs",
]

[patch.crates-io]
atat = { git = "https://github.com/BlackbirdHQ/atat", rev = "bbe146d" }
# ublox-sockets = { path = "../ublox-sockets" }