[package]
name = "ublox-cellular-rs"
version = "0.0.1"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "Driver crate for u-blox cellular devices, implementation follows 'UBX-13002752 - R65'"
readme = "../README.md"
keywords = ["arm", "cortex-m", "ublox", "cellular"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/ublox-cellular-rs"
edition = "2018"

[lib]
name = "ublox_cellular"
doctest = false

[dependencies]
heapless = { version = "^0.5", features = ["serde"] }
no-std-net = { version = "0.4.0", features = ["serde"] }
# embedded-hal = { version = "1.0.0-alpha.3" }
embedded-hal = { git = "https://github.com/MathiasKoch/embedded-hal", branch = "feature/alternative-storage" }
nb = "^1"
# atat = { version = "^0.5.1", features = ["derive"] }
# serde_at = { version = "^0.5.1" }
# atat = { git = "https://github.com/BlackbirdHQ/atat", features = ["derive"], branch = "factbird-mini-1.0" }
atat = { path = "../../atat/atat", features = ["derive"] }
serde_at = { git = "https://github.com/BlackbirdHQ/atat", branch = "factbird-mini-1.0" }
serde = { version = "^1", default-features = false, features = ["derive"] }
embedded-nal = { git = "https://github.com/MathiasKoch/embedded-nal", branch = "factbird-mini-1.0" }
typenum = "^1"
defmt = { git = "https://github.com/knurling-rs/defmt", rev = "be7f4a7cbe8a61e005f55fed1a41b11f85cb8ed6" }
hash32 = "*"
hash32-derive = "*"

[features]
default = [
    "toby-r2",
    "socket-udp",
    "socket-tcp",
    "atat/defmt-info"
]

topy-l4 = []
mpci-l2 = []
lisa-u2 = []
sara-g3 = []
sara-g4 = []
sara-u2 = []
sara-u1 = []
toby-l2 = []
toby-r2 = []
lara-r2 = []
leon-g1 = []

socket-tcp = []
socket-udp = []

defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []
