[package]
name = "ublox-cellular-rs"
version = "0.0.1"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "Driver crate for u-blox cellular devices, implementation follows 'UBX-13002752 - R65'"
readme = "../README.md"
keywords = ["arm", "cortex-m", "ublox", "cellular"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/ublox-cellular-rs"
edition = "2018"

[lib]
name = "ublox_cellular"
doctest = false

[dependencies]
heapless = { version = "^0.5", features = ["serde"] }
no-std-net = { version = "0.4.0", features = ["serde"] }
embedded-hal = { git = "https://github.com/MathiasKoch/embedded-hal", branch = "feature/alternative-storage" }
nb = "^1"
# atat = { version = "^0.5.1", features = ["derive"] }
# serde_at = { version = "^0.5.1" }
atat = { git = "https://github.com/BlackbirdHQ/atat", features = ["derive", "defmt-default"], branch = "factbird-mini-1.0" }
serde_at = { git = "https://github.com/BlackbirdHQ/atat", branch = "factbird-mini-1.0"  }
serde = { version = "^1", default-features = false, features = ["derive"] }
embedded-nal = { git = "https://github.com/MathiasKoch/embedded-nal", branch = "factbird-mini-1.0" }
typenum = "^1"
defmt = { git = "https://github.com/knurling-rs/defmt", branch = "main" }

[features]
default = ["sara_u2", "socket-udp", "socket-tcp"]

topy_l4 = []
mpci_l2 = []
lisa_u2 = []
sara_g3 = []
sara_g4 = []
sara_u2 = []
sara_u1 = []
toby_l2 = []
toby_r2 = []
lara_r2 = []
leon_g1 = []

socket-tcp = []
socket-udp = []

defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []
